# Generated by Django 5.1.6 on 2025-02-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='角色体名称')),
                ('content', models.TextField(max_length=200, verbose_name='角色体内容(json字符串)')),
                ('model_key', models.CharField(max_length=200, verbose_name='模型名称')),
                ('temperature', models.CharField(max_length=200, verbose_name='随机性')),
                ('max_tokens', models.BigIntegerField(verbose_name='单次交互所用的最大Token数')),
                ('presence_penalty', models.CharField(max_length=200, verbose_name='核采样')),
                ('top_p', models.CharField(max_length=200, verbose_name='话题新鲜度')),
                ('frequency_penalty', models.CharField(max_length=200, verbose_name='频率惩罚度')),
                ('user_icon', models.CharField(max_length=200, verbose_name='用户图标')),
                ('assistant_icon', models.CharField(max_length=200, verbose_name='助理图标')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('user_name', models.CharField(max_length=200, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '角色体',
                'verbose_name_plural': '角色体',
                'db_table': 'ai_agent',
            },
        ),
        migrations.CreateModel(
            name='AiHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='聊天记录名称')),
                ('content', models.TextField(verbose_name='聊天记录内容(json字符串)')),
                ('agent_id', models.CharField(max_length=200, verbose_name='角色体id')),
                ('all_token_counts', models.BigIntegerField(verbose_name='当前记录token数')),
                ('count', models.IntegerField(verbose_name='当前对话数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('user_name', models.CharField(max_length=200, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
                'db_table': 'ai_history',
            },
        ),
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=200, verbose_name='调用模型主键')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型显示名称')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('model_type', models.CharField(max_length=200, verbose_name='模型类型')),
                ('multimodal', models.BooleanField(default=False, verbose_name='是否多模态')),
                ('max_content_len', models.BigIntegerField(verbose_name='模型支持的最大上下文长度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('user_name', models.CharField(max_length=200, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '模型配置',
                'verbose_name_plural': '模型配置',
                'db_table': 'ai_model',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('know_name', models.CharField(max_length=200, verbose_name='know_name')),
                ('index_name', models.CharField(max_length=200, verbose_name='索引名称')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('user_name', models.CharField(max_length=200, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'knowledge',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_id', models.CharField(max_length=64, verbose_name='知识库ID')),
                ('title', models.CharField(max_length=200, verbose_name='文件标题')),
                ('file_id', models.CharField(max_length=200, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('file_size', models.CharField(max_length=200, verbose_name='文件大小(兆)')),
                ('file_path', models.CharField(max_length=255, verbose_name='文件路径(绝对路径)')),
                ('file_index_name', models.CharField(max_length=255, verbose_name='向量文件索引名')),
                ('file_index_ids', models.TextField(verbose_name='向量文件索引ID,用逗号分隔')),
                ('docment_count', models.IntegerField(verbose_name='文档数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('user_name', models.CharField(max_length=200, verbose_name='用户名')),
                ('status', models.IntegerField(default=0, verbose_name='文件状态(0上传;1解析中2向量中 3完成)')),
            ],
            options={
                'verbose_name': '知识库文件',
                'verbose_name_plural': '知识库文件',
                'db_table': 'knowledge_file',
            },
        ),
    ]
