version: '1.0'
services:
  mysql:   
    image: mysql:8.0.40-debian
    restart: always
    network_mode: "host"
    environment:
      MYSQL_DATABASE: 'ai_agent'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - "3306:3306"


  web:
    build:
      context: .
      dockerfile: dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql