# 基础镜像
FROM python:3.11.11


WORKDIR /root

# 初始化环境
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# 安装阿里的源
WORKDIR /etc/apt
# 创建文件
ADD sources.list /etc/apt
RUN apt-get clean

# 更新apt包索引并安装依赖
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    curl \
    libssl-dev \
    libffi-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libssl-dev \
    libffi-dev \
    liblzma-dev \
    nodejs \
    npm \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*
 
# 升级pip
RUN python -m pip install --upgrade pip

# 安装ModelScope
RUN pip install modelscope

# 下载向量模型
WORKDIR /root/models/bge-large-zh
RUN modelscope download --model 'BAAI/bge-large-zh' --local_dir '/root/models/bge-large-zh'


# 切换工作目录
WORKDIR /root

# 下载 HX-GPT
RUN git clone https://gitee.com/vfcm/hx_gpt.git 

# 打包npm
WORKDIR /root/hx_gpt
RUN cd /root/hx_gpt && npm install && npm run build

# 切换工作目录到 server
WORKDIR /root/hx_gpt/server
RUN echo "Files in /root/hx_gpt/server:" && ls -la /root/hx_gpt/server

# 确认 requirements.txt 存在
RUN if [ ! -f requirements.txt ]; then echo "requirements.txt not found"; exit 1; fi

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

 
# 运行管理命令
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]